export default {
  USERS_REPOSITORY: "USERS_REPOSITORY",
  PORTAL_REPOSITORY: "PORTAL_REPOSITORY",
  POSITION_REPOSITORY: "POSITION_REPOSITORY",
  DEPARTMENT_REPOSITORY: "DEPARTMENT_REPOSITORY",
  ROLES_REPOSITORY: "ROLES_REPOSITORY"
};