export default {
  USERS_REPOSITORY: "USERS_REPOSITORY",
  ROLES_REPOSITORY: "ROLES_REPOSITORY",
  USER_ROLES_REPOSITORY: "USER_ROLES_REPOSITORY",
  PORTAL_REPOSITORY: "PORTAL_REPOSITORY",
  POSITION_REPOSITORY: "POSITION_REPOSITORY",
  DEPARTMENT_REPOSITORY: "DEPARTMENT_REPOSITORY",
  APPEALS_REPOSITORY: "APPEALS_REPOSITORY",
  HRANSWERS_REPOSITORY: "HRANSWERS_REPOSITORY",
  BLOB_REPOSIRORY: "BLOB_REPOSITORY",
  TOPIC_REPOSITORY: "TOPIC_REPOSITORY",
  CDN_STORAGE: "blobCache"
};