export default {
  USERS_REPOSITORY: "USERS_REPOSITORY",
  ROLES_REPOSITORY: "ROLES_REPOSITORY",
  USER_ROLES_REPOSITORY: "USER_ROLES_REPOSITORY",
  PORTAL_REPOSITORY: "PORTAL_REPOSITORY",
  LOCALITY_REPOSITORY: "LOCALITY_REPOSITORY",
  REGION_REPOSITORY: "REGION_REPOSITORY",
  DEPARTMENT_REPOSITORY: "DEPARTMENT_REPOSITORY",
  APPEALS_REPOSITORY: "APPEALS_REPOSITORY",
  HRANSWERS_REPOSITORY: "HRANSWERS_REPOSITORY",
  BLOB_REPOSIRORY: "BLOB_REPOSITORY",
  TOPIC_REPOSITORY: "TOPIC_REPOSITORY",
  CDN_STORAGE: "blobCache",
  TEST_REPOSITORY: "TEST_REPOSITORY",
  QUESTION_REPOSITORY: "QUESTION_REPOSITORY",
  ANSWER_REPOSITORY: "ANSWER_REPOSITORY",
  INVITATION_REPOSITORY: "INVITATION_REPOSITORY",
  TEST_RESULT_REPOSITORY: "TEST_RESULT_REPOSITORY"
};